---
site:
  title: LB1347 - Advanced Features of Ansible Automation Platform
  url: https://github.com/rhpds/adv-feature-of-aap-showroom
  start_page: modules::index.adoc

content:
  sources:
    - url: .
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./content/supplemental-ui
    - path: ./content/lib
    - path: ui.yml
      contents: "static_files: [ .nojekyll, css/site-extra.css, js/buttons.js ]"

antora:
  extensions:
    - '@sntke/antora-mermaid-extension'
    - require: ./content/lib/inject-buttons.js
    - require: ./content/lib/inject-buttons.js
runtime:
  fetch: true

asciidoc:
  attributes:
    experimental: true
    page-pagination: true
    showroom-collection-version: v1.5.2

output:
  dir: ./www
