---
type: zero-touch

# Set the left column width to 30%
default_width: 30
# Persist the URL state so browser refresh doesn't reset the UI
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: '@Codeserver'
    url: '{vscode_server_url}'
  - name: '>_Terminal'
    path: /wetty
    port: 443
  - name: AAP
    url: '{controller_url}'
  - name: Gitea
    url: '{gitea_url}'
  - name: OPA
    url: "{opa_web_url}"

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Lab introduction"
      scripts: []
      solveButton: false
    - name: lab-access
      label: "Lab Access Details"
      scripts: []
      solveButton: false
    - name: module-01
      label: "Module 1: Introduction to Unified UI"
      scripts: [solve, validation]
      solveButton: true
    - name: module-02
      label: "Module 2: Configure resources with Ansible"
      scripts: [solve, validation]
      solveButton: true
    - name: module-03
      label: "Module 3: Employ AAP workflows"
      scripts: [solve, validation]
      solveButton: true
    - name: module-04
      label: "Module 4: Surveys and access rights"
      scripts: [solve, validation]
      solveButton: true
    - name: module-05
      label: "Module 5: Dynamic inventories"
      scripts: [solve, validation]
      solveButton: true
    - name: module-06
      label: "Module 6: Constructed inventory"
      scripts: [solve, validation]
      solveButton: true
    - name: module-07
      label: "Module 7: Secure the Automation Supply Chain"
      scripts: [solve, validation]
      solveButton: true
    - name: module-08
      label: "Module 8: Self-Service Automation Portal"
      scripts: [solve, validation]
      solveButton: true
    - name: module-09
      label: "Module 9: Policy Enforcement"
      scripts: [solve, validation]
      solveButton: true
    - name: the-end
      label: "The End"
      scripts: []
      solveButton: false
