= Lab Access

For your convenience, this page contains access information to all systems in your lab environment.

[#consoles]
== Graphical Consoles

[cols="1,3,1,1,1"]
|===
s| Role s| URL s| Tab s| Username s| Password 
| VS Code | {vscode_server_url}[window=blank] | @Codeserver | n/a | {vscode_server_password}
| Automation controller | {controller_url}[window=blank] | AAP | {controller_username} | {controller_password}
| Gitea web UI | {gitea_url}[window=blank] | Gitea | {gitea_username} | {gitea_password}
| Self-Service Automation Portal | {ssap_url}[window=blank] | SSAP | {controller_username} | {controller_password}
|===

The password for all systems is: **{common_password}**

NOTE: you won't directly access the OPA (Open Policy Agent) server.

[#ssh]
== SSH Details

Your primary work machine is `bastion`, which is pre-configured for any internal SSH. If you want to SSH into it instead of using VS Code, here is the information:

[cols="1,1,3,1"]
|===
s|SSH Username s|SSH Password s| SSH Host s| SSH PORT
|{ssh_username}
|{ssh_password}
|{ssh_hostname}
|{ssh_port}
|===

[source,bash,role=execute,subs=attributes+]
.SSH command:
----
{ssh_command}
----

TIP: The Showroom tab named ">_Terminal" gives you a similar look and feel as SSH, without the need to log in.
Copy works generally with kbd:[Ctrl+C] and paste with kbd:[Shift+Ctrl+V]; if not, use the right mouse button and select menu:Copy[] or menu:Paste[] from the context menu.

