= Lab Access

For your convenience, this page contains access information to all systems in your lab environment.

[#consoles]
== Graphical Consoles

[cols="1,3,1,1,1"]
|===
s| Role s| URL s| Tab s| Username s| Password 
| VS Code | {vscode_server_url}[window=blank] | @Codeserver | Null | {vscode_server_password}
| Automation controller | {controller_url}[window=blank] | AAP | {controller_username} | {controller_password}
| Gitea web UI | {gitea_url}[window=blank] | Gitea | {gitea_username} | {gitea_password}
|===

The password for all systems is: **{common_password}**

[#ssh]
== SSH Details

Your primary work machine is `bastion`, which is pre-configured for any internal SSH. If you want to SSH into it instead of using VS Code, here is the information:

[cols="1,1,3,1"]
|===
s|SSH Username s|SSH Password s| SSH Host s| SSH PORT
|{ssh_username}
|{ssh_password}
|{ssh_hostname}
|{ssh_port}
|===

[source,bash,role=execute,subs=attributes+]
.SSH command:
----
{ssh_command}
----

TIP: the Showroom tab named "Terminal" gives you a similar look & feel as would SSH, without the need to login.
Copy works generally with Ctrl+C and Paste with Shift+Ctrl+V; if not, simply use the right mouse button and select Copy resp. Paste from the menu.

